name: Build WP Theme + Plugin
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build React project
        run: npm run build

      # ---------- THEME ----------
      - name: Prepare WordPress theme folder
        run: |
          mkdir -p history-scout-wp/dist
          cp -r dist/* history-scout-wp/dist/
          cat > history-scout-wp/style.css <<'EOF'
          /*
          Theme Name: History Scout WP
          Theme URI: https://github.com/zeeshanenterpriseslvt-dev/history-scout-ai
          Author: You
          Description: WordPress theme version of History Scout AI site
          Version: 1.0
          */
          EOF
          cat > history-scout-wp/functions.php <<'EOF'
          <?php
          function history_scout_enqueue_assets() {
              $theme_dir = get_template_directory_uri();
              $css_files = glob(get_template_directory() . '/dist/assets/index-*.css');
              if ($css_files) {
                  $css_file = basename($css_files[0]);
                  wp_enqueue_style('history-scout-style', $theme_dir . '/dist/assets/' . $css_file);
              }
              $js_files = glob(get_template_directory() . '/dist/assets/index-*.js');
              if ($js_files) {
                  $js_file = basename($js_files[0]);
                  wp_enqueue_script('history-scout-script', $theme_dir . '/dist/assets/' . $js_file, array(), null, true);
              }
          }
          add_action('wp_enqueue_scripts', 'history_scout_enqueue_assets');
          EOF
          cat > history-scout-wp/index.php <<'EOF'
          <?php get_header(); ?>
          <div id="root">
            <noscript>⚠️ React build not found or JavaScript disabled.</noscript>
          </div>
          <?php get_footer(); ?>
          EOF

      - name: Zip WP theme (fixed structure)
        run: |
          mkdir -p build-theme
          cp -r history-scout-wp build-theme/
          cd build-theme
          zip -r ../history-scout-wp.zip history-scout-wp
          cd ..

      - name: Upload theme artifact
        uses: actions/upload-artifact@v4
        with:
          name: history-scout-wp
          path: history-scout-wp.zip

      # ---------- PLUGIN ----------
      - name: Prepare WordPress plugin folder
        run: |
          mkdir -p ai-research-suite-admin/includes
          cat > ai-research-suite-admin/ai-research-suite-admin.php <<'EOF'
          <?php
          /*
          Plugin Name: AI Research Suite (Admin)
          Description: Admin interface for configuring and testing AI Research Suite API integration.
          Version: 1.1
          Author: You
          */
          if ( ! defined( 'ABSPATH' ) ) exit;
          define('ARS_ADMIN_DIR', plugin_dir_path(__FILE__));
          require_once ARS_ADMIN_DIR . 'includes/admin.php';
          require_once ARS_ADMIN_DIR . 'includes/ajax.php';
          require_once ARS_ADMIN_DIR . 'includes/dashboard.php';
          EOF
          cat > ai-research-suite-admin/includes/admin.php <<'EOF'
          <?php
          if ( ! defined( 'ABSPATH' ) ) exit;
          function ars_admin_menu() {
              add_menu_page('AI Research Suite', 'AI Research Suite', 'manage_options', 'ars-admin', 'ars_admin_page');
          }
          add_action('admin_menu', 'ars_admin_menu');
          function ars_admin_page() {
              ?>
              <div class="wrap">
                  <h1>AI Research Suite Settings</h1>
                  <form method="post" action="options.php">
                      <?php settings_fields('ars_settings'); do_settings_sections('ars_settings'); ?>
                      <table class="form-table">
                          <tr><th>OpenAI API Key</th><td><input type="text" name="ars_api_key" value="<?php echo esc_attr(get_option('ars_api_key')); ?>" size="50"/></td></tr>
                          <tr><th>Default Model</th><td>
                              <select name="ars_model">
                                  <option value="gpt-3.5-turbo" <?php selected(get_option('ars_model'),'gpt-3.5-turbo'); ?>>gpt-3.5-turbo</option>
                                  <option value="gpt-4" <?php selected(get_option('ars_model'),'gpt-4'); ?>>gpt-4</option>
                              </select>
                          </td></tr>
                      </table>
                      <?php submit_button(); ?>
                  </form>
              </div>
              <?php
          }
          function ars_register_settings() {
              register_setting('ars_settings','ars_api_key');
              register_setting('ars_settings','ars_model');
          }
          add_action('admin_init','ars_register_settings');
          EOF
          cat > ai-research-suite-admin/includes/ajax.php <<'EOF'
          <?php
          if ( ! defined( 'ABSPATH' ) ) exit;
          add_action('wp_ajax_ars_admin_test','ars_admin_test_callback');
          function ars_admin_test_callback() {
              check_ajax_referer('ars_nonce');
              $api_key = get_option('ars_api_key');
              $model = get_option('ars_model','gpt-3.5-turbo');
              $prompt = sanitize_text_field($_POST['prompt'] ?? 'Hello!');
              $response = wp_remote_post('https://api.openai.com/v1/chat/completions',array(
                  'headers'=>array('Authorization'=>'Bearer '.$api_key,'Content-Type'=>'application/json'),
                  'body'=>json_encode(array('model'=>$model,'messages'=>array(array('role'=>'user','content'=>$prompt)),'max_tokens'=>200))
              ));
              if(is_wp_error($response)){ wp_send_json_error(array('message'=>$response->get_error_message())); }
              else {
                  $body = wp_remote_retrieve_body($response);
                  $data = json_decode($body,true);
                  $answer = $data['choices'][0]['message']['content'] ?? 'No response';
                  wp_send_json_success(array('answer'=>$answer));
              }
          }
          EOF
          cat > ai-research-suite-admin/includes/dashboard.php <<'EOF'
          <?php
          if ( ! defined( 'ABSPATH' ) ) exit;
          function ars_admin_add_dashboard_widget() {
              wp_add_dashboard_widget('ars_admin_dashboard_widget','AI Research Suite Test','ars_admin_dashboard_widget_render');
          }
          add_action('wp_dashboard_setup','ars_admin_add_dashboard_widget');
          function ars_admin_dashboard_widget_render() { ?>
              <p>Click to test OpenAI API connection.</p>
              <button id="ars-test-btn" class="button">Run Test</button>
              <div id="ars-test-result"></div>
              <script>
              (function(){
                document.getElementById('ars-test-btn').addEventListener('click',function(){
                  var box=document.getElementById('ars-test-result');
                  box.innerText='⏳ Running test...';
                  var data=new FormData();
                  data.append('action','ars_admin_test');
                  data.append('nonce','<?php echo wp_create_nonce('ars_nonce'); ?>');
                  data.append('prompt','Say hello in one sentence');
                  fetch(ajaxurl,{method:'POST',body:data})
                  .then(r=>r.json()).then(j=>{
                    if(j.success){ box.innerText='✅ '+j.data.answer; }
                    else { box.innerText='❌ Error'; }
                  }).catch(e=>{box.innerText='❌ Failed';});
                });
              })();
              </script>
          <?php }
          EOF

      - name: Zip WP plugin
        run: |
          mkdir -p build-plugin
          cp -r ai-research-suite-admin build-plugin/
          cd build-plugin
          zip -r ../ai-research-suite-admin.zip ai-research-suite-admin
          cd ..

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-research-suite-admin
          path: ai-research-suite-admin.zip
