name: Build WP Theme
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build React project
        run: npm run build

      - name: Prepare WordPress theme folder
        run: |
          mkdir -p history-scout-wp/dist
          cp -r dist/* history-scout-wp/dist/
          cat > history-scout-wp/style.css <<'EOF'
          /*
          Theme Name: History Scout WP
          Theme URI: https://github.com/zeeshanenterpriseslvt-dev/history-scout-ai
          Author: You
          Description: WordPress theme version of History Scout AI site
          Version: 1.0
          */
          EOF
          cat > history-scout-wp/functions.php <<'EOF'
          <?php
          function history_scout_enqueue_assets() {
              $theme_dir = get_template_directory_uri();
              $css_files = glob(get_template_directory() . '/dist/assets/index-*.css');
              if ($css_files) {
                  $css_file = basename($css_files[0]);
                  wp_enqueue_style('history-scout-style', $theme_dir . '/dist/assets/' . $css_file);
              }
              $js_files = glob(get_template_directory() . '/dist/assets/index-*.js');
              if ($js_files) {
                  $js_file = basename($js_files[0]);
                  wp_enqueue_script('history-scout-script', $theme_dir . '/dist/assets/' . $js_file, array(), null, true);
              }
          }
          add_action('wp_enqueue_scripts', 'history_scout_enqueue_assets');
          EOF
          cat > history-scout-wp/index.php <<'EOF'
          <?php get_header(); ?>
          <div id="root">
            <noscript>⚠️ React build not found or JavaScript disabled.</noscript>
          </div>
          <?php get_footer(); ?>
          EOF

      - name: Zip WP theme
        run: zip -r history-scout-wp.zip history-scout-wp

      - name: Upload theme artifact
        uses: actions/upload-artifact@v4
        with:
          name: history-scout-wp
          path: history-scout-wp.zip
